vpn_info_dictionary = [
    {
    'Номер':1,
    'Название на Android':'AdGuard VPN',
    'Название на IOS':'AdGuard VPN – Unlimited & Fast',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['AdGuard VPN'],
    'Названия в базе на IOS':['AdGuard VPN – Unlimited & Fast']
    },
    {
    'Номер':2,
    'Название на Android':'Антивирус - очиститель + ВПН',
    'Название на IOS':'Antivirus - Cleaner + VPN',
    'Другие названия на Android':['Antivirus - Cleaner + VPN'],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Антивирус - очиститель + ВПН', 'Antivirus - Cleaner + VPN'],
    'Названия в базе на IOS':['Antivirus - Cleaner + VPN']
    },
    {
    'Номер':3,
    'Название на Android':'Atlas VPN: ВПН для мобильного',
    'Название на IOS':'Atlas ВПН:быстрый и безопасный',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Atlas VPN: ВПН для мобильного'],
    'Названия в базе на IOS':['Atlas ВПН:быстрый и безопасный']
    },
    {
    'Номер': 4,
    'Название на Android':'Betternet VPN - Hotspot Proxy',
    'Название на IOS':'VPN/ВПН прокси Betternet',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Betternet VPN - Hotspot Proxy'],
    'Названия в базе на IOS':['VPN/ВПН прокси Betternet']
    },
    {
    'Номер': 5,
    'Название на Android':'BigMama - VPN',
    'Название на IOS':'BigMama VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['BigMama - VPN'],
    'Названия в базе на IOS':['BigMama VPN']
    },
    {
    'Номер': 6,
    'Название на Android':'1.1.1.1: Faster&Safer Internet',
    'Название на IOS':'1.1.1.1: Faster Internet',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['1.1.1.1: Faster&Safer Internet'],
    'Названия в базе на IOS':['1.1.1.1: Faster Internet']
    },
    {
    'Номер': 7,
    'Название на Android':'VPN Express VPN - Быстрый ВПН',
    'Название на IOS':'VPN ExpressVPN - Быстрый ВПН',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Express VPN - Быстрый ВПН'],
    'Названия в базе на IOS':['VPN ExpressVPN - Быстрый ВПН']
    },
    {
    'Номер': 8,
    'Название на Android':'Free VPN by Free VPN .org',
    'Название на IOS':'Free VPN by Free VPN .org',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Free VPN by Free VPN .org'],
    'Названия в базе на IOS':['Free VPN by Free VPN .org']
    },
    {
    'Номер':9,
    'Название на Android':'GeckoVPN Unlimited Proxy VPN',
    'Название на IOS':'Gecko VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['GeckoVPN Unlimited Proxy VPN'],
    'Названия в базе на IOS':['Gecko VPN']
    },
    {
    'Номер':10 ,
    'Название на Android':'VPN быстро и безопасно GoVPN',
    'Название на IOS':'Go VPN - Super Fast VPN Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN быстро и безопасно GoVPN'],
    'Названия в базе на IOS':['Go VPN - Super Fast VPN Proxy']
    },
    {
    'Номер': 11,
    'Название на Android':'HideMyAss VPN',
    'Название на IOS':'HideMyAss VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['HideMyAss VPN'],
    'Названия в базе на IOS':['HideMyAss VPN']
    },
    {
    'Номер': 12,
    'Название на Android':'Hola VPN',
    'Название на IOS':'Hola VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Hola VPN'],
    'Названия в базе на IOS':['Hola VPN']
    },
    {
    'Номер': 13,
    'Название на Android':'HotBot VPN Быстро и безопасно',
    'Название на IOS':'HotBot VPN | Прокси.',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['HotBot VPN Быстро и безопасно'],
    'Названия в базе на IOS':['HotBot VPN | Прокси.']
    },
    {
    'Номер': 14,
    'Название на Android':'IPVanish VPN: The Fastest VPN',
    'Название на IOS':'IPVanish VPN: The Fastest VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['IPVanish VPN: The Fastest VPN'],
    'Названия в базе на IOS':['IPVanish VPN: The Fastest VPN']
    },
# 15-й номер (KeepSolid VPN) удален
    {
    'Номер':16,
    'Название на Android':'KeyVPN AppLock - Бесплатный VPN',
    'Название на IOS':'Key VPN',
    'Другие названия на Android':['KeyVPN AppLock - Бесплатный VPN'],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['KeyVPN AppLock - Бесплатный VP', 'KeyVPN AppLock - Бесплатный VPN'],
    'Названия в базе на IOS':['Key VPN']
    },
    {
    'Номер': 17,
    'Название на Android':'Krot.io VPN',
    'Название на IOS':'Krot.io VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Krot.io VPN'],
    'Названия в базе на IOS':['Krot.io VPN']
    },
    {
    'Номер': 18,
    'Название на Android':'KUTO VPN - Очень быстрый VPN',
    'Название на IOS':'Kuto VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['KUTO VPN - Очень быстрый VPN'],
    'Названия в базе на IOS':['Kuto VPN']
    },
    {
    'Номер':19,
    'Название на Android':'Lantern: Лучше, чем VPN',
    'Название на IOS':'Lantern VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Lantern: Лучше, чем VPN'],
    'Названия в базе на IOS':['Lantern VPN']
    },
    {
    'Номер': 20,
    'Название на Android':'Near VPN',
    'Название на IOS':'NearVPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Near VPN'],
    'Названия в базе на IOS':['NearVPN']
    },
    {
    'Номер': 21,
    'Название на Android':'Nord VPN: VPN без ограничений',
    'Название на IOS':'Nord VPN: быстрый и лучший ВПН',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Nord VPN: VPN без ограничений'],
    'Названия в базе на IOS':['Nord VPN: быстрый и лучший ВПН']
    },
    {
    'Номер': 22,
    'Название на Android':'OpenVPN Connect - OpenVPN App (Vypr VPN)',
    'Название на IOS':'OpenVPN Connect (Vypr VPN)',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['OpenVPN Connect - OpenVPN App (Vypr VPN)', 'OpenVPN Connect - OpenVPN App'],
    'Названия в базе на IOS':['OpenVPN Connect (Vypr VPN)', 'OpenVPN Connect - OpenVPN App']
    },
    {
    'Номер':23,
    'Название на Android':'Opera VPN',
    'Название на IOS':'Opera VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Opera VPN'],
    'Названия в базе на IOS':['Opera VPN']
    },
    {
    'Номер':24,
    'Название на Android':'Private Tunnel VPN - Fast & Secure Cloud VPN',
    'Название на IOS':'Private Tunnel VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Private Tunnel VPN - Fast & Secure Cloud VPN'],
    'Названия в базе на IOS':['Private Tunnel VPN']
    },
    {
    'Номер':25,
    'Название на Android':'Psiphon Pro',
    'Название на IOS':'Psiphon',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Psiphon Pro'],
    'Названия в базе на IOS':['Psiphon']
    },
    {
    'Номер': 26,
    'Название на Android':'RavoVPN-Secure&Fast Proxy',
    'Название на IOS':'Ravo VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['RavoVPN-Secure&Fast Proxy'],
    'Названия в базе на IOS':['Ravo VPN']
    },
    {
    'Номер':27,
    'Название на Android':'Red Shield VPN',
    'Название на IOS':'Red Shield VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Red Shield VPN'],
    'Названия в базе на IOS':['Red Shield VPN']
    },
    {
    'Номер': 28,
    'Название на Android':'RiseupVPN',
    'Название на IOS':'Riseup VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['RiseupVPN'],
    'Названия в базе на IOS':['Riseup VPN']
    },
    {
    'Номер': 29,
    'Название на Android':'Secure VPN - Безопаснее, быстрее',
    'Название на IOS':'SecureVPN - Защита Данных',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Secure VPN - Безопаснее, быстрее'],
    'Названия в базе на IOS':['SecureVPN - Защита Данных']
    },
    {
    'Номер': 30,
    'Название на Android':'Security Master',
    'Название на IOS':'Security Master',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Security Master'],
    'Названия в базе на IOS':['Security Master']
    },
    {
    'Номер': 31,
    'Название на Android':'Sky VPN - быстрый безопасныйVPN',
    'Название на IOS':'Sky VPN: Безлимитный VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Sky VPN - быстрый безопасныйVPN'],
    'Названия в базе на IOS':['Sky VPN: Безлимитный VPN']
    },
    {
    'Номер': 32,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Solo VPN- Proxy Betternet',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Solo VPN- Proxy Betternet']
    },
    {
    'Номер': 33,
    'Название на Android':'Speedify - Live Streaming VPN',
    'Название на IOS':'Speedify',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Speedify - Live Streaming VPN'],
    'Названия в базе на IOS':['Speedify']
    },
    {
    'Номер': 34,
    'Название на Android':'SuperVPN - Unlimited Proxy',
    'Название на IOS':'Super VPN - Secure VPN Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['SuperVPN - Unlimited Proxy'],
    'Названия в базе на IOS':['Super VPN - Secure VPN Proxy']
    },
    {
    'Номер':35,
    'Название на Android':'Tachyon VPN - Private Proxy',
    'Название на IOS':'Tachyon VPN - Private Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tachyon VPN - Private Proxy'],
    'Названия в базе на IOS':['Tachyon VPN - Private Proxy']
    },
    {
    'Номер': 36,
    'Название на Android':'Thunder VPN: Более быстрый VPN',
    'Название на IOS':'Thunder VPN - VPN for iPhone',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Thunder VPN: Более быстрый VPN'],
    'Названия в базе на IOS':['Thunder VPN - VPN for iPhone']
    },
    {
    'Номер':37,
    'Название на Android':'Tik VPN: быстрый и безлимитный',
    'Название на IOS':'TikVPN-Безлимитный прокси ВПН',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tik VPN: быстрый и безлимитный'],
    'Названия в базе на IOS':['TikVPN-Безлимитный прокси ВПН']
    },
    {
    'Номер':38,
    'Название на Android':'Tiny VPN',
    'Название на IOS':'Tiny VPN - Ultra Fast',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tiny VPN'],
    'Названия в базе на IOS':['Tiny VPN - Ultra Fast']
    },
    {
    'Номер':39,
    'Название на Android':'Private & Secure VPN: TorGuard',
    'Название на IOS':'Private & Secure VPN: TorGuard',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Private & Secure VPN: TorGuard'],
    'Названия в базе на IOS':['Private & Secure VPN: TorGuard']
    },
    {
    'Номер': 40,
    'Название на Android':'Touch VPN - VPN Proxy & Privacy',
    'Название на IOS':'TouchVPN – Безграничный Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Touch VPN - VPN Proxy & Privacy'],
    'Названия в базе на IOS':['TouchVPN – Безграничный Proxy']
    },
    {
    'Номер': 41,
    'Название на Android':'Trust.Zone VPN - Anonymous VPN',
    'Название на IOS':'Trust.Zone VPN - Anonymous VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Trust.Zone VPN - Anonymous VPN'],
    'Названия в базе на IOS':['Trust.Zone VPN - Anonymous VPN']
    },
    {
    'Номер': 42,
    'Название на Android':'Tube VPN-Secure&Fast&Stable',
    'Название на IOS':'Tube VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tube VPN-Secure&Fast&Stable'],
    'Названия в базе на IOS':['Tube VPN']
    },
    {
    'Номер': 43,
    'Название на Android':'TunnelBear: Secure VPN & Wifi',
    'Название на IOS':'TunnelBear: Secure VPN & Wifi',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['TunnelBear: Secure VPN & Wifi'],
    'Названия в базе на IOS':['TunnelBear: Secure VPN & Wifi']
    },
    {
    'Номер':44,
    'Название на Android':'Turbo VPN - безопасный ВПН',
    'Название на IOS':'Turbo VPN приватный браузер',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Turbo VPN - безопасный ВПН'],
    'Названия в базе на IOS':['Turbo VPN приватный браузер']
    },
    {
    'Номер':45,
    'Название на Android':'UFO VPN',
    'Название на IOS':'UFO VPN - Супер VPN-Сервис',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['UFO VPN'],
    'Названия в базе на IOS':['UFO VPN - Супер VPN-Сервис']
    },
    {
    'Номер':46,
    'Название на Android':'Ultimate VPN',
    'Название на IOS':'Ultimate VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Ultimate VPN'],
    'Названия в базе на IOS':['Ultimate VPN']
    },
    {
    'Номер': 47,
    'Название на Android':'베일덕 VPN - 빠르고 안전한 VPN',
    'Название на IOS':'VeilDuck VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['베일덕 VPN - 빠르고 안전한 VPN'],
    'Названия в базе на IOS':['VeilDuck VPN']
    },
    {
    'Номер': 48,
    'Название на Android':'VPN GO - Private Net Access',
    'Название на IOS':'VPN GO - Private VPN for Net',
    'Другие названия на Android':['NetGO - Private Net Access'],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['NetGO - Private Net Access', 'VPN GO - Private Net Access'],
    'Названия в базе на IOS':['VPN GO - Private VPN for Net']
    },
    {
    'Номер':49,
    'Название на Android':'VPN Proxy Master: Super Vpn',
    'Название на IOS':'VPN Master Неограниченный прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Proxy Master: Super Vpn'],
    'Названия в базе на IOS':['VPN Master Неограниченный прокси']
    },
    {
    'Номер':50,
    'Название на Android':'VPN.lat: Unlimited and Secure',
    'Название на IOS':'VPN_Lat',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN.lat: Unlimited and Secure'],
    'Названия в базе на IOS':['VPN_Lat']
    },
    {
    'Номер': 51,
    'Название на Android':'VPN Private - Fast VPN Master',
    'Название на IOS':'VPN Private',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Private - Fast VPN Master'],
    'Названия в базе на IOS':['VPN Private']
    },
    {
    'Номер':52,
    'Название на Android':'vpnify',
    'Название на IOS':'VPNIFY - Unlimited VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['vpnify'],
    'Названия в базе на IOS':['VPNIFY - Unlimited VPN']
    },
    {
    'Номер':53,
    'Название на Android':'Vypr VPN: VPN и приватность',
    'Название на IOS':'Vypr VPN: VPN и приватность',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Vypr VPN: VPN и приватность'],
    'Названия в базе на IOS':['Vypr VPN: VPN и приватность']
    },
    {
    'Номер':54,
    'Название на Android':'Windscribe VPN',
    'Название на IOS':'Windscribe VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Windscribe VPN'],
    'Названия в базе на IOS':['Windscribe VPN']
    },
    {
    'Номер':55,
    'Название на Android':'X-VPN - Private Browser VPN',
    'Название на IOS':'X-VPN - Best VPN Proxy master',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['X-VPN - Private Browser VPN'],
    'Названия в базе на IOS':['X-VPN - Best VPN Proxy master']
    },
    {
    'Номер': 56,
    'Название на Android':'Vast VPN - Fast & Secure',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Vast VPN - Fast & Secure'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 57,
    'Название на Android':'WiFi Map®: Find Internet, VPN',
    'Название на IOS':'WiFi Map: Internet, eSIM, VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['WiFi Map®: Find Internet, VPN'],
    'Названия в базе на IOS':['WiFi Map: Internet, eSIM, VPN']
    },
    {
    'Номер': 58,
    'Название на Android':'VPN PotatoVPN - WiFi Proxy',
    'Название на IOS':'VPN PotatoVPN -Fast WiFi Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN PotatoVPN - WiFi Proxy'],
    'Названия в базе на IOS':['VPN PotatoVPN -Fast WiFi Proxy']
    },
    {
    'Номер':59,
    'Название на Android':'VPN Бобер сервис ВПН',
    'Название на IOS':'VPN Мастер – ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Бобер сервис ВПН'],
    'Названия в базе на IOS':['VPN Мастер – ВПН прокси']
    },
    {
    'Номер':60,
    'Название на Android':'hidemy.name VPN',
    'Название на IOS':'hidemy.name VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['hidemy.name VPN'],
    'Названия в базе на IOS':['hidemy.name VPN']
    },
    {
    'Номер':61,
    'Название на Android':'Star VPN: Unlimited WiFi Proxy',
    'Название на IOS':'Star VPN: Unlimited WiFi Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Star VPN: Unlimited WiFi Proxy'],
    'Названия в базе на IOS':['Star VPN: Unlimited WiFi Proxy']
    },
    {
    'Номер':62,
    'Название на Android':'Surfshark VPN - мобильный ВПН',
    'Название на IOS':'VPN Surfshark - ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Surfshark VPN - мобильный ВПН'],
    'Названия в базе на IOS':['VPN Surfshark - ВПН прокси']
    },
    {
    'Номер':63,
    'Название на Android':'Melon VPN - Прокси-VPN',
    'Название на IOS':'Melon VPN - Easy Fast VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Melon VPN - Прокси-VPN'],
    'Названия в базе на IOS':['Melon VPN - Easy Fast VPN']
    },
    {
    'Номер':64,
    'Название на Android':'Proton VPN: Private, secure',
    'Название на IOS':'OpenVPN Connect (Proton VPN)',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Proton VPN: Private, secure'],
    'Названия в базе на IOS':['Proton VPN: Fast & Secure', 'OpenVPN Connect (Proton VPN)'],
    },
    {
    'Номер':65,
    'Название на Android':'Tomato VPN | VPN Proxy',
    'Название на IOS':'VPN Tomato Pro - Fast & Secure',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tomato VPN | VPN Proxy'],
    'Названия в базе на IOS':['VPN Tomato - Unlimited Proxy', 'VPN Tomato Pro - Fast & Secure']
    },
    {
    'Номер': 66,
    'Название на Android':'VPN сервис от VPN Monster',
    'Название на IOS':'OpenVPN Connect (VPN Monster)',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN сервис от VPN Monster'],
    'Названия в базе на IOS':['OpenVPN Connect (VPN Monster)']
    },
    {
    'Номер': 67,
    'Название на Android':'McAfee Security: Antivirus VPN',
    'Название на IOS':'McAfee Security: VPN и защита',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['McAfee Security: Antivirus VPN'],
    'Названия в базе на IOS':['McAfee Security: VPN и защита']
    },
    {
    'Номер': 68,
    'Название на Android':'Aloha Браузер + Private VPN',
    'Название на IOS':'Aloha Browser: браузер VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Aloha Браузер + Private VPN'],
    'Названия в базе на IOS':['Aloha Browser: браузер VPN']
    },
    {
    'Номер':69,
    'Название на Android':'ZenMate VPN - быстрый и безопасный',
    'Название на IOS':'ZenMate ВПН и прокси-сервер',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['ZenMate VPN - быстрый и безопа', 'ZenMate VPN - быстрый и безопасный'],
    'Названия в базе на IOS':['ZenMate ВПН и прокси-сервер']
    },
    {
    'Номер': 70,
    'Название на Android':'Ultrasurf - Fast Unlimited VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Ultrasurf - Fast Unlimited VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 72,
    'Название на Android':'GreenNet: Hotspot VPN Proxy',
    'Название на IOS':'GreenNet VPN Proxy & Unlimited',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['GreenNet: Hotspot VPN Proxy'],
    'Названия в базе на IOS':['GreenNet VPN Proxy & Unlimited']
    },
    {
    'Номер': 73,
    'Название на Android':'VPNhub: безлимитно и безопасно',
    'Название на IOS':'VPNHUB - Лучший прокси VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPNhub: безлимитно и безопасно'],
    'Названия в базе на IOS':['VPNHUB - Лучший прокси VPN']
    },
    {
    'Номер': 74,
    'Название на Android':'Browsec VPN: ВПН, анонимайзер',
    'Название на IOS':'Browsec VPN: Безлимитный ВПН',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Browsec VPN: ВПН, анонимайзер'],
    'Названия в базе на IOS':['Browsec VPN: Безлимитный ВПН']
    },
    {
    'Номер': 75,
    'Название на Android':'VPN – Super Unlimited Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN – Super Unlimited Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 76,
    'Название на Android':'VPN Россия (VPN RedCat)',
    'Название на IOS':'VPN RedCat быстрый ВНП сервис',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Россия - ВПН Сервис безлим', 'VPN Россия (VPN RedCat)'],
    'Названия в базе на IOS':['VPN RedCat быстрый ВНП сервис']
    },
    {
    'Номер': 77,
    'Название на Android':'SecVPN Proxy Tool',
    'Название на IOS':'SecVPN: Trusted Secure VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['SecVPN Proxy Tool'],
    'Названия в базе на IOS':['SecVPN: Trusted Secure VPN']
    },
    {
    'Номер': 78,
    'Название на Android':'VPN by CyberGhost: Secure Wi-fi',
    'Название на IOS':'CyberGhost VPN/ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN by CyberGhost: Secure Wi-fi'],
    'Названия в базе на IOS':['CyberGhost VPN/ВПН прокси']
    },
    {
    'Номер': 79,
    'Название на Android':'Urban VPN Proxy Unlocker',
    'Название на IOS':'Urban VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Urban VPN Proxy Unlocker'],
    'Названия в базе на IOS':['Urban VPN']
    },
    {
    'Номер': 80,
    'Название на Android':'Speedy Quark VPN - VPN Master',
    'Название на IOS':'Speedy Quark VPN - VPN Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Speedy Quark VPN - VPN Master'],
    'Названия в базе на IOS':['Speedy Quark VPN - VPN Proxy']
    },
    {
    'Номер':81,
    'Название на Android':'впн инстаграм - Proxy Master',
    'Название на IOS':'Мастер VPN – Супер быстрый VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['впн инстаграм - Proxy Master'],
    'Названия в базе на IOS':['Мастер VPN – Супер быстрый VPN']
    },
    {
    'Номер': 82,
    'Название на Android':'VPN Fast - супер впн россия',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Fast - супер впн россия'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 83,
    'Название на Android':'VPN Pro: безопасно и быстро',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Pro: безопасно и быстро'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 84,
    'Название на Android':'Fast VPN - Fast & Secure Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Fast VPN - Fast & Secure Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 85,
    'Название на Android':'VPN Master Pro - Fast & Secure',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Master Pro - Fast & Secure'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 86,
    'Название на Android':'VPN Ukraine - Get Ukrainian IP',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Ukraine - Get Ukrainian IP'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 87,
    'Название на Android':'VPN Master - Hotspot VPN Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Master - Hotspot VPN Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 88,
    'Название на Android':'iTop VPN Proxy & Game Booster',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['iTop VPN Proxy & Game Booster'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 89,
    'Название на Android':'Snap VPN: Super Fast VPN Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['Snap VPN: Super Fast VPN Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':90,
    'Название на Android':'Отсутствует',
    'Название на IOS':'RayVPN Lite: Unlimited Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['RayVPN Lite: Unlimited Proxy']
    },
    {
    'Номер':91,
    'Название на Android':'Отсутствует',
    'Название на IOS':'ТОР БРАУЗЕР: TOR Browser + VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['ТОР БРАУЗЕР: TOR Browser + VPN']
    },
    {
    'Номер':92,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Тор браузер: OrNET онион + впн',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Тор браузер: OrNET онион + впн']
    },
    {
    'Номер':93,
    'Название на Android':'Отсутствует',
    'Название на IOS':'ВПН Мастер: VPN Прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['ВПН Мастер: VPN Прокси']
    },
    {
    'Номер':94,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Wirevpn – безлимитный VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Wirevpn – безлимитный VPN']
    },
    {
    'Номер':95,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN-AmanVPN / ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN-AmanVPN / ВПН прокси']
    },
    {
    'Номер':96,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN Speed-Fast Unlimited Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN Speed-Fast Unlimited Proxy']
    },
    {
    'Номер':97,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN Proxy Master – ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN Proxy Master – ВПН прокси']
    },
    {
    'Номер':98,
    'Название на Android':'VPN Proxy - Secure VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['VPN Proxy - Secure VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':99,
    'Название на Android':'VPN Master - fast proxy VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['VPN Master - fast proxy VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':100,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN Master – Fast Proxy Server',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN Master – Fast Proxy Server']
    },
    {
    'Номер':101,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN Bucks – лучший впн прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN Bucks – лучший впн прокси']
    },
    {
    'Номер':102,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN - Secure Super Fast VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN - Secure Super Fast VPN']
    },
    {
    'Номер':103,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN - Master VPN/ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN - Master VPN/ВПН прокси']
    },
    {
    'Номер':104,
    'Название на Android':'Unblock Websites - VPN Proxy A',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Unblock Websites - VPN Proxy A'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':105,
    'Название на Android':'SuperVPN Fast VPN Client',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['SuperVPN Fast VPN Client'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':106,
    'Название на Android':'SuperNet VPN - Fast VPN Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['SuperNet VPN - Fast VPN Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':107,
    'Название на Android':'Signal Secure VPN -Fast VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Signal Secure VPN -Fast VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':108,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Secure VPN Proxy – Fast Server',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Secure VPN Proxy – Fast Server']
    },
    {
    'Номер':109,
    'Название на Android':'Planet VPN: быстро и безопасно',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Planet VPN: быстро и безопасно'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':110,
    'Название на Android':'Phone Guardian',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Phone Guardian'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':111,
    'Название на Android':'Отсутствует',
    'Название на IOS':'PandaVPN Lite - лучший VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['PandaVPN Lite - лучший VPN']
    },
    {
    'Номер':112,
    'Название на Android':'Отсутствует',
    'Название на IOS':'nthLink',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['nthLink']
    },
    {
    'Номер':113,
    'Название на Android':'Master VPN - ВПН для Андроид',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Master VPN - ВПН для Андроид'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':114,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Master Lite – Proxy Server',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Master Lite – Proxy Server']
    },
    {
    'Номер':115,
    'Название на Android':'Kiwi VPN Connection IP Changer',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Kiwi VPN Connection IP Changer'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':116,
    'Название на Android':'HotspotShield VPN & Wifi Proxy',
    'Название на IOS':'HotspotShield VPN & Wifi Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['HotspotShield VPN & Wifi Proxy'],
    'Названия в базе на IOS':['HotspotShield VPN & Wifi Proxy']
    },
    {
    'Номер':117,
    'Название на Android':'Отсутствует',
    'Название на IOS':'hide.me VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['hide.me VPN']
    },
    {
    'Номер':118,
    'Название на Android':'Отсутствует',
    'Название на IOS':'HaloVPN: Fast Secure VPN Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['HaloVPN: Fast Secure VPN Proxy']
    },
    {
    'Номер':119,
    'Название на Android':'Goat VPN - Super Fast&Safe VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':['Goat VPN - Super Fast&Safe VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':120,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Fast VPN: Best Proxy Master',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Fast VPN: Best Proxy Master']
    },
    {
    'Номер':121,
    'Название на Android':'Daily VPN - безопасный VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Daily VPN - безопасный VPN'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':122,
    'Название на Android':'Отсутствует',
    'Название на IOS':'360 VPN - Privacy & Security',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': False,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['360 VPN - Privacy & Security']
    },
    {
    'Номер':123,
    'Название на Android':'VPN Master - Fast Secure Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Master - Fast Secure Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 124,
    'Название на Android':'VPN Russia - Unblock VPN Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Russia - Unblock VPN Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер':125,
    'Название на Android':'Tomato VPN - Hotspot VPN Proxy',
    'Название на IOS':'Tomato VPN - Hotspot VPN Proxy',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['Tomato VPN - Hotspot VPN Proxy'],
    'Названия в базе на IOS':['Tomato VPN - Hotspot VPN Proxy']
    },
    {
    'Номер': 126,
    'Название на Android':'SoloVPN - One Tap Proxy',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':['SoloVPN - One Tap Proxy'],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 127,
    'Название на Android':'Отсутствует',
    'Название на IOS':'Ultrasurf VPN',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['Ultrasurf VPN']
    },
    {
    'Номер': 128,
    'Название на Android':'Отсутствует',
    'Название на IOS':'VPN - Super VPN/ВПН прокси',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'01.10.2022',
    'Блокируется': True,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':['VPN - Super VPN/ВПН прокси']
    },
    {
    'Номер':129,
    'Название на Android':'VPN Unlimited – Proxy Shield',
    'Название на IOS':'VPN Unlimited - Proxy Master',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений':'21.03.2023',
    'Блокируется': True,
    'Названия в базе на Android':['VPN Unlimited – Proxy Shield'],
    'Названия в базе на IOS':['VPN Unlimited - Proxy Master']
    },
    {
    'Номер': 130,
    'Название на Android': 'VPN Proxy - Super VPN Master',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.02.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': [],
    },
    # новая партия от 01.05.2023
    {
    'Номер': 131,
    'Название на Android':'AnonymoX VPN',
    'Название на IOS':'Отсутствует',
    'Другие названия на Android':[],
    'Другие названия на IOS':[],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android':[],
    'Названия в базе на IOS':[]
    },
    {
    'Номер': 132,
    'Название на Android': 'Avira Phantom VPN',
    'Название на IOS': 'Avira Phantom VPN & Wifi Proxy',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 133,
    'Название на Android': 'CandyLink VPN',
    'Название на IOS': 'Candylink VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['CandyLink VPN',],
    'Названия в базе на IOS': ['Candylink VPN',]
    },
    {
    'Номер': 134,
    'Название на Android': 'FishVPN - Безопасность Прокси',
    'Название на IOS': 'FishVPN - Безопасность Прокси',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 135,
    'Название на Android': 'Freedom VPN',
    'Название на IOS': 'Freedom-VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Freedom VPN',],
    'Названия в базе на IOS': ['Freedom-VPN',]
    },
    {
    'Номер': 136,
    'Название на Android': 'Garuda VPN',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 137,
    'Название на Android': 'Hoxx VPN',
    'Название на IOS': 'Hoxx VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Hoxx VPN',],
    'Названия в базе на IOS': ['Hoxx VPN',]
    },
    {
    'Номер': 138,
    'Название на Android': 'Отсутствует',
    'Название на IOS': 'iCloud private relay',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': ['iCloud private relay',]
    },
    {
    'Номер': 139,
    'Название на Android': 'Insta VPN - Fast Private VPN',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Insta VPN - Fast Private VPN',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 140,
    'Название на Android': 'LomVPN',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['LomVPN',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 141,
    'Название на Android': 'metaVPN – надежен и безлимитен',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['metaVPN – надежен и безлимитен',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 142,
    'Название на Android': 'Mullvad VPN',
    'Название на IOS': 'Mullvad VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Mullvad VPN',],
    'Названия в базе на IOS': ['Mullvad VPN',]
    },
    {
    'Номер': 143,
    'Название на Android': 'Steganos VPN Online Shield',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Steganos VPN Online Shield'],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 144,
    'Название на Android': 'Seed4.Me VPN Proxy',
    'Название на IOS': 'VPN Proxy by Seed4.Me VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Seed4.Me VPN Proxy',],
    'Названия в базе на IOS': ['VPN Proxy by Seed4.Me VPN',]
    },
    {
    'Номер': 145,
    'Название на Android': 'Отсутствует',
    'Название на IOS': 'Snap VPN - Super VPN Browser',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': ['Snap VPN - Super VPN Browser',]
    },
    {
    'Номер': 146,
    'Название на Android': 'Unblock Websites - VPN by uVPN',
    'Название на IOS': 'uVPN: Super Fast Secure VPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Unblock Websites - VPN by uVPN',],
    'Названия в базе на IOS': ['uVPN: Super Fast Secure VPN',]
    },
    {
    'Номер': 147,
    'Название на Android': 'VPN - Super VPN Proxy Master',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['VPN - Super VPN Proxy Master',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 148,
    'Название на Android': 'OpenVPN Connect (VPN Gate)',
    'Название на IOS': 'OpenVPN Connect (VPN Gate)',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['OpenVPN Connect (VPN Gate)',],
    'Названия в базе на IOS': ['OpenVPN Connect (VPN Gate)',]
    },
    {
    'Номер': 149,
    'Название на Android': 'VPN Proxy Speed - Super VPN',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['VPN Proxy Speed - Super VPN',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 150,
    'Название на Android': 'VPN Super Proxy - Proxy Master',
    'Название на IOS': 'VPN Super Proxy - Proxy Master',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 151,
    'Название на Android': 'Отсутствует',
    'Название на IOS': 'RelyVPN - WiFi Proxy Master',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': ['RelyVPN - WiFi Proxy Master',]
    },
    {
    'Номер': 152,
    'Название на Android': 'Yoga VPN - безопасный прокси',
    'Название на IOS': 'Yoga VPN - Protect Security',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['Yoga VPN - безопасный прокси',],
    'Названия в базе на IOS': ['Yoga VPN - Protect Security',]
    },
    {
    'Номер': 153,
    'Название на Android': 'PrivateVPN',
    'Название на IOS': 'PrivateVPN',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': True,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['PrivateVPN',],
    'Названия в базе на IOS': ['PrivateVPN',]
    },
    {
    'Номер': 154,
    'Название на Android': 'FlashVPN Fast VPN Proxy',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['FlashVPN Fast VPN Proxy',],
    'Названия в базе на IOS': []
    },
    {
    'Номер':155,
    'Название на Android': 'VPN Bucks - Fast VPN Proxy',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': True,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['VPN Bucks - Fast VPN Proxy',],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 156,
    'Название на Android': 'VPN Turkey - VPN в Турции',
    'Название на IOS': 'Отсутствует',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': ['VPN Turkey - VPN в Турции'],
    'Названия в базе на IOS': []
    },
    {
    'Номер': 157,
    'Название на Android': 'VPN - Super VPN Proxy',
    'Название на IOS': 'VPN - Super VPN Proxy',
    'Другие названия на Android': [],
    'Другие названия на IOS': [],
    'Наличие в магазине Android': False,
    'Наличие в магазине IOS': False,
    'Дата начала измерений': '01.05.2023',
    'Блокируется': True,
    'Названия в базе на Android': [],
    'Названия в базе на IOS': []
    },

]



 	


    # ,
    # {
    # 'Номер':,
    # 'Название на Android':'',
    # 'Название на IOS':'',
    # 'Другие названия на Android':[],
    # 'Другие названия на IOS':[],
    # 'Наличие в магазине Android': ,
    # 'Наличие в магазине IOS': ,
    # 'Дата начала измерений':'',
    # 'Блокируется': ,
    # 'Названия в базе на Android':[],
    # 'Названия в базе на IOS':[]
    # }





















