# Generated by Django 3.2.18 on 2023-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('vpn_performance_$viewset1', 'vpn performance $viewset1'), ('map_$viewset1', 'map $viewset1'), ('interactive_chart_$viewset1', 'interactive chart $viewset1'), ('access_to_blocked_resources_$viewset1', 'access to blocked resources $viewset1'), ('reports_and_documents_$viewset1', 'reports and documents $viewset1'))},
        ),
    ]
