# Generated by Django 3.2.18 on 2024-01-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('vpn_performance', 'vpn performance'), ('map', 'map'), ('interactive_chart', 'interactive chart'), ('access_to_blocked_resources', 'access to blocked resources'), ('reports_and_documents', 'reports and documents'), ('new_func', 'new function'), ('archive', 'archive'), ('main_page', 'main page'), ('analytics', 'analytics'))},
        ),
    ]
